name: protoype_t_a
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  firebase_core: 2.9.0
  firebase_auth: 4.4.0
  cloud_firestore: 4.5.0
  firebase_storage: 11.1.0
  flutter: 
    sdk: flutter
  local_auth: ^2.1.6
  email_auth: ^1.0.0
  image_picker: ^0.8.7+3
  path_provider: ^2.0.14
  convex_bottom_bar: ^3.2.0
  simple_navigation_menu: ^0.2.0
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  file_picker: ^5.3.1
  expendable_fab: ^0.0.1
  circular_menu : any
  syncfusion_flutter_datepicker: ^21.2.3
  flutter_lock_screen: ^2.0.1
  flutter_screen_lock: ^9.0.1
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - Assets/image/pei 1.png
    - Assets/image/getpass.jpg
    - Assets/image/peiPutih.png
    - Assets/image/Exp1.png
    - Assets/image/exp2.png
    - Assets/image/lock.jpg
    - Assets/image/girlWithPohne.png
    - Assets/image/Rectangle 29.png
    - Assets/image/White_fingeprint.png
    - Assets/image/emailverif.jpg
    - Assets/image/Ikhsan.jpg
    - Assets/icon/check icon.png
    - Assets/icon/Failed Icon.png
    - Assets/icon/Warning icon.png
    - Assets/icon/Hand.png
    - Assets/icon/location.png
  fonts: 
    - family: Lexend
      fonts: 
        - asset: Assets/font/Lexend-VariableFont_wght.ttf
  uses-material-design: true

