// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWzPEIN6t9zgz2JCIOqNx2lNORQgybbPo',
    appId: '1:950578543441:web:5f3041c78de72b0de53170',
    messagingSenderId: '950578543441',
    projectId: 'presensi-ddd76',
    authDomain: 'presensi-ddd76.firebaseapp.com',
    storageBucket: 'presensi-ddd76.appspot.com',
    measurementId: 'G-14MHR2H140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMG2b9zgLeBUpGy80qqP9lNkVpyx5Vms',
    appId: '1:950578543441:android:2efac338a328b99fe53170',
    messagingSenderId: '950578543441',
    projectId: 'presensi-ddd76',
    storageBucket: 'presensi-ddd76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_egGZXTono7wCq62ejLEgKe3OgNwHw5c',
    appId: '1:950578543441:ios:919294299f86aa71e53170',
    messagingSenderId: '950578543441',
    projectId: 'presensi-ddd76',
    storageBucket: 'presensi-ddd76.appspot.com',
    iosClientId: '950578543441-t7k7sb0ekjvfc7ctn9e1hdulecr9porm.apps.googleusercontent.com',
    iosBundleId: 'com.proTA.protoypeTa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_egGZXTono7wCq62ejLEgKe3OgNwHw5c',
    appId: '1:950578543441:ios:919294299f86aa71e53170',
    messagingSenderId: '950578543441',
    projectId: 'presensi-ddd76',
    storageBucket: 'presensi-ddd76.appspot.com',
    iosClientId: '950578543441-t7k7sb0ekjvfc7ctn9e1hdulecr9porm.apps.googleusercontent.com',
    iosBundleId: 'com.proTA.protoypeTa',
  );
}
